In [1]:
from numpy import array
from numpy import load
from numpy import eye
from numpy import tril
from numpy import triu
from numpy import diag
from numpy import set_printoptions
from numpy import inf
from numpy.linalg import norm
from numpy.linalg import det
import numpy as np
from metodes_directes import qr_house, ldlt



### Exercici 1
Llegiu la matriu $A$ (diagonalmant dominant) i el vector $b$ del fitxer
`sistemaedd.npz` amb les instruccions:
```Python
from numpy import load
file = "../../Documents/universitat/kolmogorov/aln/tasca_sistemes_lineals/sistemaedd.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
print(f"Vector b:\n{b}\n")
data.close() # Cal tanquer el fitxer un cop s'han llegit les dades
```
<!--
Comproveu que és no singular calculant el determinant,
```python
detA = np.linalg.det(A)
``` 
Tanquem el fitxer un cop s'ha llegit les dades
```python
data.close()
```
-->
Apliqueu la funció `lu` per donar la factorització $LU$ de la matriu $A$. A
partir de la matriu tornada per la funció `lu`, obtingueu explícitament les
matrius $L$ i $U$. Calculeu també la norma del vector residual de la
descomposició, 
$$
    \mathtt{res} := \| A - LU \|_{\infty}.
$$
Amb la factorització $LU$ trobada de la matriu $A$, calculeu, fent ús de la
funció `sol_lu`, la solució, $\mathring{x}$, del sistema $A x = b$. Doneu també
la norma del vector residual, 
$$
 \mathtt{res} := \left\| b - A \mathring{x} \right\|_{\infty}.
$$ 

#### Solució

### Exercici 2
Llegiu la matriu $A$ i el vector $b$ del fitxer `sistema.npz` amb les
instruccions:
```Python
from numpy import load
file = "sistema.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")
```
Tanqueu el fitxer un cop s'han llegit les dades:
```python
data.close()
```
Comproveu que és no singular calculant el determinant,
```python
from numpy.linalg import det
detA = det(A)
print(f"Determinant de la matriu A: {detA}\n")
``` 
Apliqueu la funció `lu_pp` per trobar la factorització $LU$ de la matriu
$A$ amb pivot parcial ($PA = LU$). A partir de la matriu tornada per la
funció `lu_pp`, obtingueu explícitament les matrius $L$ i $U$. Calculem
també la norma del vector residual de la descomposició, 
$$
    \mathtt{res} := \| PA - LU \|_{\infty}.
$$
Amb la factorització $LU$ trobada de la matriu $PA$, calculeu, fent ús de la
funció `sol_lu`, la solució, $\mathring{x}$, del sistema $A x = b$. Doneu també
la norma del vector residual, 
$$
 \mathtt{res} := \left\| b - A \mathring{x} \right\|_{\infty}.
$$ 

#### Solució

### Exercici 3
Llegiu la matriu $A$ i el vector $b$ del fitxer `sistema.npz` amb les
instruccions:
```Python
from numpy import load
file = "sistema.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")
```
Tanqueu el fitxer un cop s'han llegit les dades:
```python
data.close()
```
Comproveu que és no singular calculant el determinant,
```python
from numpy.linalg import det
detA = det(A)
print(f"Determinant de la matriu A: {detA}\n")
``` 
Apliqueu la funció `lu_ppe` per trobar la factorització $LU$ de la matriu $A$
amb pivot parcial esglaonat ($PA = LU$). A partir de la matriu tornada per la
funció `lu_ppe`, obtingueu explícitament les matrius $L$ i $U$. Calculem també la
norma del vector residual de la descomposició, 
$$
    \mathtt{res} := \| PA - LU \|_{\infty}.
$$
Amb la factorització $LU$ trobada de la matriu $PA$, calculeu, fent ús de la
funció `sol_lu`, la solució, $\mathring{x}$, del sistema $A x = b$. Doneu també
la norma del vector residual, 
$$
 \mathtt{res} := \left\| b - A \mathring{x} \right\|_{\infty}.
$$ 

#### Solució

### Exercici 4
Llegiu la matriu $A$, estrictament diagonal dominant, i el vector $b$ del
fitxer `sistemaedd.npz` amb les instruccions:
```Python
from numpy import load
file = "sistemaedd.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")
data.close() # Tanqueu el fitxer un cop s'han llegit les dades:
``` 
Apliqueu la funció `doolittle` per trobar la factorització $LU$ de la
matriu $A$ ($A = LU$) amb el mètode de Doolittle. A partir de la matriu
tornada per la funció, obtingueu explícitament les matrius $L$ i $U$.
Calculem també la norma del vector residual de la descomposició, 
$$
    \mathtt{res} := \| PA - LU \|_{\infty}.
$$
Amb la factorització $LU$ trobada de la matriu $A$, calculeu, fent ús de
la funció `sol_lu`, la solució, $\mathring{x}$, del sistema $A x = b$. Doneu
també la norma del vector residual, 
$$
 \mathtt{res} := \left\| b - A \mathring{x} \right\|_{\infty}.
$$ 

#### Solució

### Exercici 5
Llegiu la matriu $A$, estrictament diagonal dominant, i el vector $b$ del
fitxer `sistemaedd.npz` amb les instruccions:
```Python
from numpy import load
file = "sistemaedd.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")
data.close() # Tanqueu el fitxer un cop s'han llegit les dades:
``` 
Apliqueu la funció `crout` per trobar la factorització $LU$ de la matriu
$A$ ($A = LU$) amb el mètode de Crout. A partir de la matriu tornada per la
funció, obtingueu explícitament les matrius $L$ i $U$. Calculem també la
norma del vector residual de la descomposició, 
$$
    \mathtt{res} := \| PA - LU \|_{\infty}.
$$
Amb la factorització $LU$ trobada de la matriu $A$, calculeu, fent ús de la
funció `sol_lu` (modificada convenientment), la solució, $\mathring{x}$, del
sistema $A x = b$. Doneu també la norma del vector residual, 
$$
 \mathtt{res} := \left\| b - A \mathring{x} \right\|_{\infty}.
$$ 

#### Solució

### Exercici 6
Llegiu la matriu $A$, simètrica definida positiva, i el vector $b$ del
fitxer `sistemasdp.npz` amb les instruccions:
```Python
from numpy import load
file = "sistemasdp.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")
data.close() # Tanqueu el fitxer un cop s'han llegit les dades
```
Apliqueu la funció `ldlt` per trobar la factorització $LDL^{\top}$ de la matriu
$A$ ($A = LDL^{\top}$) amb el mètode de \texttt{LDLT}. A partir de la matriu
tornada per la funció, obtingueu explícitament les matrius $L$ i $D$. Calculem
també la norma del vector residual de la descomposició, 
$$
    \mathtt{res} := \| A - LDL^{\top} \|_{\infty}.
$$
Amb la factorització $LDL^{\top}$ trobada de la matriu $A$, trobeu la solució,
$\mathring{x}$, del sistema $A x = b$. Doneu també la norma del vector residual,
$$
 \mathtt{res} := \left\| b - A \mathring{x} \right\|_{\infty}.
$$ 


#### Solució

In [2]:
from numpy import load
file = "data/sistemasdp.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")

n = A.shape[0]
A_original = A.copy()

ldlt(A)
D = np.diag(np.diag(A))
L = np.tril(A, k=-1) + np.eye(n)
`
print(norm(A_original - L @ D @ L.T, ord=np.inf))


data.close() # Tanqueu el fitxer un cop s'han llegit les dades

Fichero: data/sistemasdp.npz
Claves: ['matriu_sistema', 'vector']

D [[62.91797957  0.          0.         ...  0.          0.
   0.        ]
 [ 0.         63.67021935  0.         ...  0.          0.
   0.        ]
 [ 0.          0.         64.4743751  ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ... 54.67379726  0.
   0.        ]
 [ 0.          0.          0.         ...  0.         54.49858723
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
  54.96416779]]
L [[1.         0.         0.         ... 0.         0.         0.        ]
 [0.16357542 1.         0.         ... 0.         0.         0.        ]
 [0.16578102 0.17648007 1.         ... 0.         0.         0.        ]
 ...
 [0.19311388 0.16858066 0.16904267 ... 1.         0.         0.        ]
 [0.1849325  0.17923934 0.14919675 ... 0.03589926 1.         0.        ]
 [0.17232977 0.14759584 0.15235823 ... 0.02611333 0.02510397 1.        ]]
9.237055564881302e-14


### Exercici 7
Llegiu la matriu $A$, simètrica definida positiva, i el vector $b$ del
fitxer `sistemasdp.npz` amb les instruccions:
```Python
from numpy import load
file = "sistemasdp.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")
data.close() # Tanqueu el fitxer un cop s'han llegit les dades
```
Apliqueu la funció `cholesky` per trobar la factorització $LL^{\top}$ de la matriu
$A$ ($A = LL^{\top}$) amb el mètode de Choleski. A partir de la matriu tornada per
la funció, obtingueu explícitament la matriu $L$. Calculem també la
norma del vector residual de la descomposició, 
$$
    \mathtt{res} := \| PA - LL^{\top} \|_{\infty}.
$$
Amb la factorització $LL^{\top}$ trobada de la matriu $A$, Tanqueu,
$\mathring{x}$, del sistema $A x = b$. Doneu també la norma del vector residual,
$$
 \mathtt{res} := \left\| b - A \mathring{x} \right\|_{\infty}.
$$ 


#### Solució

### Exercici 8 
Llegiu la matriu $A$ del fitxer fitxer `sistema.npz` amb les instruccions:
```Python
from numpy import load
file = "sistema.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")
```
Tanqueu el fitxer un cop s'han llegit les dades
```Python
data.close()  
```
Comproveu que és no singular calculant el determinant,
```python
from numpy.linalg import det
detA = det(A)
print(f"Determinant de la matriu A: {detA}\n")
``` 
Apliqueu la funció `gs_classic` per trobar la factorització $QR$ de la matriu
$A$ ($A = QR$) amb el mètode clàssic de Gram-Schmidt.

Treieu explícitament les matrius $Q$ i $R$, i calculeu el residu de la
ortogonalitat de $Q$, i.e.,  
$$
    \mathtt{res} := \| I - Q^{\top}Q \|_{2},
$$
i també el residu de la factorització, i.e.,
$$
    \mathtt{res} := \| A - QR \|_{2}.
$$ 

#### Solució

### Exercici 9 
Llegiu la matriu $A$ del fitxer fitxer `sistema.npz` amb les instruccions:
```Python
from numpy import load
file = "sistema.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")
```
Tanqueu el fitxer un cop s'han llegit les dades
```Python
data.close()  
```
Comproveu que és no singular calculant el determinant,
```python
from numpy.linalg import det
detA = det(A)
print(f"Determinant de la matriu A: {detA}\n")
``` 
Apliqueu la funció `gs_modificat` per trobar la factorització $QR$ de la matriu
$A$ ($A = QR$) amb el mètode modificat de Gram-Schmidt.

Treieu explícitament les matrius $Q$ i $R$, i calculeu el residu de la ortogonalitat de $Q$, i.e.,
$$
    \mathtt{res} := \| I - Q^{\top}Q \|_{2},
$$
i també el residu de la factorització, i.e.,
$$
    \mathtt{res} := \| A - QR \|_{2}.
$$ 

#### Solució

### Exercici 10  
Llegiu la matriu $A$ del fitxer fitxer `sistema.npz` amb les instruccions:
```Python
from numpy import load
file = "sistema.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A = data[data.files[0]]
#print(f"Matriu A:\n{A}\n")
b = data[data.files[1]]
#print(f"Vector b:\n{b}\n")
```
Tanqueu el fitxer un cop s'han llegit les dades
```Python
data.close()  
```
Comproveu que és no singular calculant el determinant,
```python
from numpy.linalg import det
detA = det(A)
print(f"Determinant de la matriu A: {detA}\n")
``` 
Apliqueu la funció `qr_house` per trobar la factorització $QR$ de la matriu
$A$ ($A = QR$) amb el mètode de Householder.

Treieu explícitament les matrius $Q$ i $R$, i calculeu el residu de la
ortogonalitat de $Q$, i.e., 
$$
    \mathtt{res} := \| I - Q^{\top}Q \|_{2},
$$
i també el residu de la factorització, i.e.,
$$
    \mathtt{res} := \| A - QR \|_{2}.
$$

#### Solució

In [3]:
from metodes_directes import house
import numpy as np
from numpy import load
file = "data/sistema.npz"
data = load(file)
print(f"Fichero: {file}\nClaves: {data.files}\n")
A: np.ndarray = data[data.files[0]]
b = data[data.files[1]]

from numpy.linalg import det
detA = det(A)
print(f"Determinant de la matriu A: {detA}\n")

x = np.array([10, 40, 30, -10, 23], dtype=float)
beta, u = house(x)
H = np.eye(len(x)) - beta * np.outer(u, u)
print(H)
print(H @ x)

A_original = A.copy()
m, n = A.shape
Q, R = qr_house(A)

print("Q", Q)
print("R", R)
print(norm(np.eye(m) - Q.T @ Q))
print(norm(A - Q @ R))
data.close()

Fichero: data/sistema.npz
Claves: ['matriu_sistema', 'vector']

Determinant de la matriu A: 154859.3203317212

[[-0.17598108 -0.70392432 -0.52794324  0.17598108 -0.40475648]
 [-0.70392432  0.57864165 -0.31601876  0.10533959 -0.24228105]
 [-0.52794324 -0.31601876  0.76298593  0.07900469 -0.18171079]
 [ 0.17598108  0.10533959  0.07900469  0.9736651   0.06057026]
 [-0.40475648 -0.24228105 -0.18171079  0.06057026  0.8606884 ]]
[-5.68242906e+01 -1.05471187e-15  2.19269047e-15 -1.51267887e-15
  1.11022302e-15]
Q [[-0.04807062  0.04568972  0.26401748 ... -0.26753301 -0.14712063
   0.44629807]
 [-0.21848048 -0.01336186 -0.19678892 ... -0.2765282   0.1720728
   0.22833359]
 [-0.19869304 -0.09834638 -0.25322993 ... -0.04324971  0.25662149
  -0.04179208]
 ...
 [-0.14342327 -0.11922224  0.0559082  ... -0.18482028 -0.10198765
   0.04473327]
 [-0.15806482 -0.08065842  0.00718249 ...  0.16822836 -0.10888947
  -0.08051445]
 [-0.00814637 -0.21842743  0.278403   ...  0.04821667  0.00070734
  -0.15623763